package de.kopfzentrum.gam.inventory;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import java.net.URI;import java.net.http.*;import java.time.Duration;import java.util.*;

@Service
public class HomeAssistantDeviceSource {
  private static final Logger log=LoggerFactory.getLogger(HomeAssistantDeviceSource.class);
  private final HomeAssistantSettingsRepository settings; private final ObjectMapper json;
  public HomeAssistantDeviceSource(HomeAssistantSettingsRepository settings,ObjectMapper json){this.settings=settings;this.json=json;}
  public Result load(){var sources=settings.loadEnabledInternal();if(sources.isEmpty())return new Result(List.of(),"SKIPPED","Keine aktive Home-Assistant-Quelle konfiguriert");List<HaDevice> all=new ArrayList<>();List<String> errors=new ArrayList<>();int ok=0;for(var s:sources){try{all.addAll(loadOne(s));ok++;}catch(Exception e){log.warn("Home Assistant {} fehlgeschlagen: {}",s.name(),e.toString());errors.add(s.name()+": "+Objects.toString(e.getMessage(),"Fehler"));}}Map<String,HaDevice> unique=new LinkedHashMap<>();for(var d:all)unique.putIfAbsent(d.identityKey(),d);String status=ok==0?"FAILED":errors.isEmpty()?"COMPLETED":"COMPLETED";return new Result(new ArrayList<>(unique.values()),status,ok+" von "+sources.size()+" Home-Assistant-Quellen geladen, "+unique.size()+" Geräte"+(errors.isEmpty()?"":"; "+String.join(" | ",errors)));}
  public TestResult test(long id){var s=settings.loadOne(id);if(!s.enabled())return new TestResult(id,s.name(),false,"SKIPPED","Quelle ist deaktiviert.",s.baseUrl(),"",0,List.of());if(s.accessToken().isBlank())return new TestResult(id,s.name(),false,"CONFIGURATION","Long-Lived Access Token fehlt.",s.baseUrl(),"",0,List.of());try{HttpClient c=client();JsonNode config=get(c,s,"/api/config");List<HaDevice> devices=loadStates(c,s);List<String> preview=devices.stream().map(d->d.name()+" · "+d.type()).distinct().limit(10).toList();return new TestResult(id,s.name(),true,"COMPLETED","Verbindung und Authentifizierung erfolgreich.",s.baseUrl(),config.path("version").asText(""),devices.size(),preview);}catch(Exception e){return new TestResult(id,s.name(),false,"FAILED",friendly(e),s.baseUrl(),"",0,List.of());}}
  public List<HaDevice> loadSource(long sourceId)throws Exception{return loadOne(settings.loadOne(sourceId));}
  private List<HaDevice> loadOne(HomeAssistantSettingsRepository.Settings s)throws Exception{HttpClient c=client();get(c,s,"/api/config");return loadStates(c,s);}
  private List<HaDevice> loadStates(HttpClient c,HomeAssistantSettingsRepository.Settings s)throws Exception{JsonNode states=get(c,s,"/api/states");List<HaDevice> out=new ArrayList<>();for(JsonNode n:states){String entity=n.path("entity_id").asText("");JsonNode a=n.path("attributes");String domain=entity.contains(".")?entity.substring(0,entity.indexOf('.')):"";String name=text(a,"friendly_name",entity);String manufacturer=first(a,"manufacturer","manufacturer_name","vendor");String model=first(a,"model","model_name","device_model");String ip=first(a,"ip_address","ip","host","local_ip");String mac=first(a,"mac_address","mac","macaddress");String deviceClass=first(a,"device_class");String type=classify(domain,deviceClass,name,manufacturer,model);
      boolean deviceLike=Set.of("camera","media_player","climate","vacuum","fan","light","lock","cover","alarm_control_panel","water_heater","remote","siren").contains(domain)||!ip.isBlank()||!mac.isBlank()||!manufacturer.isBlank()||!model.isBlank();
      if(!deviceLike)continue;String state=n.path("state").asText("");boolean online=!Set.of("unavailable","unknown").contains(state);out.add(new HaDevice(s.id(),s.name(),s.location(),entity,name,type,ip,normalizeMac(mac),manufacturer,model,online));}
    Map<String,HaDevice> u=new LinkedHashMap<>();for(HaDevice d:out)u.merge(d.identityKey(),d,(a,b)->prefer(a,b));return new ArrayList<>(u.values());}
  private static HaDevice prefer(HaDevice a,HaDevice b){return score(b)>score(a)?b:a;}private static int score(HaDevice d){return (d.ip().isBlank()?0:4)+(d.mac().isBlank()?0:5)+(d.manufacturer().isBlank()?0:2)+(d.model().isBlank()?0:2)+(d.type().startsWith("Home Assistant")?0:3);}
  private JsonNode get(HttpClient c,HomeAssistantSettingsRepository.Settings s,String path)throws Exception{HttpRequest r=HttpRequest.newBuilder(URI.create(s.baseUrl()+path)).timeout(Duration.ofSeconds(12)).header("Authorization","Bearer "+s.accessToken()).header("Content-Type","application/json").GET().build();HttpResponse<String> res=c.send(r,HttpResponse.BodyHandlers.ofString());if(res.statusCode()==401||res.statusCode()==403)throw new IllegalStateException("Authentifizierung fehlgeschlagen (HTTP "+res.statusCode()+")");if(res.statusCode()<200||res.statusCode()>=300)throw new IllegalStateException("HTTP "+res.statusCode()+" von "+path);return json.readTree(res.body());}
  private static HttpClient client(){return HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(6)).followRedirects(HttpClient.Redirect.NORMAL).build();}
  public static String classify(String domain,String dc,String name,String manufacturer,String model){String x=(domain+" "+dc+" "+name+" "+manufacturer+" "+model).toLowerCase(Locale.ROOT);if(x.contains("printer")||x.contains("drucker")||x.contains("epson")||x.contains("brother")||x.contains("canon")||x.contains("laserjet"))return "Drucker / Multifunktionsgerät";if(domain.equals("camera")||x.contains("camera")||x.contains("kamera")||x.contains("onvif"))return "Kamera / Videoüberwachung";if(domain.equals("vacuum")||x.contains("vacuum")||x.contains("saugroboter")||x.contains("mower")||x.contains("mähroboter"))return "Robotik";if(domain.equals("media_player")||x.contains("receiver")||x.contains("denon")||x.contains("sonos")||x.contains("speaker")||x.contains("tv"))return "Audio & Receiver";if(domain.equals("climate")||x.contains("thermostat")||x.contains("klima")||x.contains("heat pump")||x.contains("wärmepumpe"))return "Klima & Gebäudetechnik";if(x.contains("dishwasher")||x.contains("geschirrsp")||x.contains("washing machine")||x.contains("waschmaschine")||x.contains("dryer")||x.contains("trockner")||x.contains("home connect"))return "Haushaltsgeräte";if(x.contains("inverter")||x.contains("wechselrichter")||x.contains("battery")||x.contains("batterie")||x.contains("photovolta")||x.contains("solar")||x.contains("kostal")||x.contains("felicity"))return "Energie / Wechselrichter";if(x.contains("nas")||x.contains("synology")||x.contains("diskstation")||x.contains("qnap"))return "NAS / Speicher";if(x.contains("switch")||x.contains("router")||x.contains("access point")||x.contains("fritz!box")||x.contains("cisco"))return "Netzwerkgerät";if(x.contains("windows")||x.contains("computer")||x.contains("desktop")||x.contains("laptop")||x.contains("notebook"))return "Computer";return "Home Assistant Gerät";}
  private static String friendly(Exception e){String m=Objects.toString(e.getMessage(),"");if(m.contains("Authentifizierung"))return m;if(m.contains("Connect")||m.contains("refused")||m.contains("timed out"))return "Home Assistant ist unter der angegebenen URL nicht erreichbar.";return m.isBlank()?e.getClass().getSimpleName():m;}
  private static String text(JsonNode a,String k,String f){String x=a.path(k).asText("");return x.isBlank()?f:x;}private static String first(JsonNode a,String...ks){for(String k:ks){String x=a.path(k).asText("");if(!x.isBlank())return x;}return "";}private static String normalizeMac(String x){return x==null?"":x.replace('-',':').toUpperCase(Locale.ROOT);}
  public record HaDevice(long sourceId,String sourceName,String location,String entityId,String name,String type,String ip,String mac,String manufacturer,String model,boolean online){String identityKey(){if(!mac.isBlank())return "mac:"+mac;if(!ip.isBlank())return "ip:"+sourceId+":"+ip;return "entity:"+sourceId+":"+entityId;}}
  public record Result(List<HaDevice> devices,String status,String message){}
  public record TestResult(long sourceId,String sourceName,boolean success,String status,String message,String baseUrl,String version,int deviceCount,List<String> devicePreview){}
}
