package de.kopfzentrum.gam.invoice;

/**
 * Legacy placeholder after step 37i.
 *
 * The former OpenPDF/iText based implementation has been retired.  This class
 * intentionally contains no Spring annotations and no OpenPDF imports.  It is
 * kept only so that stale source trees which still contain references to the
 * old filename are overwritten during zip extraction.
 *
 * Productive invoice PDFs are generated by {@link InvoiceOpenHtmlPdfService}
 * and finalized with ZUGFeRD/Factur-X through the Zugferd export service.
 */
@Deprecated(forRemoval = false)
public final class InvoicePdfService {
  private InvoicePdfService() {
    throw new UnsupportedOperationException("OpenPDF invoice export was removed in Schritt 37i. Use InvoiceOpenHtmlPdfService/ZugferdExportService.");
  }
}
