package de.kopfzentrum.gam.invoice;
import jakarta.annotation.PostConstruct;
import java.math.BigDecimal;
import java.sql.ResultSet;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
@Repository public class PaymentWorkflowSettingsRepository {
 private final JdbcTemplate jdbc; public PaymentWorkflowSettingsRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @PostConstruct void init(){jdbc.execute("CREATE TABLE IF NOT EXISTS gam_settings (setting_key VARCHAR(120) NOT NULL, setting_value TEXT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, updated_by VARCHAR(255) NULL, PRIMARY KEY(setting_key))"); saveDefaults();}
 private void saveDefaults(){PaymentWorkflowSettings d=PaymentWorkflowSettings.defaults(); putMissing("payment.partial.enabled",d.partialPaymentsEnabled());putMissing("payment.installments.count",d.defaultInstallmentCount());putMissing("payment.installments.intervalDays",d.installmentIntervalDays());putMissing("payment.installments.minimum",d.minimumInstallmentAmount());putMissing("payment.termDays",d.paymentTermDays());putMissing("payment.reminder.enabled",d.reminderEnabled());putMissing("payment.reminder.days",d.reminderDaysAfterDue());putMissing("payment.dunning1.enabled",d.dunning1Enabled());putMissing("payment.dunning1.days",d.dunning1DaysAfterReminder());putMissing("payment.dunning1.fee",d.dunning1Fee());putMissing("payment.dunning2.enabled",d.dunning2Enabled());putMissing("payment.dunning2.days",d.dunning2DaysAfterDunning1());putMissing("payment.dunning2.fee",d.dunning2Fee());putMissing("payment.dunning3.enabled",d.dunning3Enabled());putMissing("payment.dunning3.days",d.dunning3DaysAfterDunning2());putMissing("payment.dunning3.fee",d.dunning3Fee());putMissing("payment.collection.enabled",d.collectionEnabled());putMissing("payment.collection.days",d.collectionDaysAfterDunning3());putMissing("payment.interest.annualPercent",d.annualInterestPercent());putMissing("payment.documents.automatic",d.automaticDocumentCreation());putMissing("payment.documents.manualApproval",d.manualApprovalRequired());putMissing("payment.portal.publish",d.publishToPortal());putMissing("payment.portal.readAloud",d.portalReadAloudEnabled());putMissing("payment.email.automatic",d.automaticEmailDispatch());}
 public PaymentWorkflowSettings load(){var d=PaymentWorkflowSettings.defaults();return new PaymentWorkflowSettings(b("payment.partial.enabled",d.partialPaymentsEnabled()),i("payment.installments.count",d.defaultInstallmentCount()),i("payment.installments.intervalDays",d.installmentIntervalDays()),n("payment.installments.minimum",d.minimumInstallmentAmount()),i("payment.termDays",d.paymentTermDays()),b("payment.reminder.enabled",d.reminderEnabled()),i("payment.reminder.days",d.reminderDaysAfterDue()),b("payment.dunning1.enabled",d.dunning1Enabled()),i("payment.dunning1.days",d.dunning1DaysAfterReminder()),n("payment.dunning1.fee",d.dunning1Fee()),b("payment.dunning2.enabled",d.dunning2Enabled()),i("payment.dunning2.days",d.dunning2DaysAfterDunning1()),n("payment.dunning2.fee",d.dunning2Fee()),b("payment.dunning3.enabled",d.dunning3Enabled()),i("payment.dunning3.days",d.dunning3DaysAfterDunning2()),n("payment.dunning3.fee",d.dunning3Fee()),b("payment.collection.enabled",d.collectionEnabled()),i("payment.collection.days",d.collectionDaysAfterDunning3()),n("payment.interest.annualPercent",d.annualInterestPercent()),b("payment.documents.automatic",d.automaticDocumentCreation()),b("payment.documents.manualApproval",d.manualApprovalRequired()),b("payment.portal.publish",d.publishToPortal()),b("payment.portal.readAloud",d.portalReadAloudEnabled()),b("payment.email.automatic",d.automaticEmailDispatch()));}
 public PaymentWorkflowSettings save(PaymentWorkflowSettings v,String u){String[] k={"payment.partial.enabled","payment.installments.count","payment.installments.intervalDays","payment.installments.minimum","payment.termDays","payment.reminder.enabled","payment.reminder.days","payment.dunning1.enabled","payment.dunning1.days","payment.dunning1.fee","payment.dunning2.enabled","payment.dunning2.days","payment.dunning2.fee","payment.dunning3.enabled","payment.dunning3.days","payment.dunning3.fee","payment.collection.enabled","payment.collection.days","payment.interest.annualPercent","payment.documents.automatic","payment.documents.manualApproval","payment.portal.publish","payment.portal.readAloud","payment.email.automatic"};Object[] x={v.partialPaymentsEnabled(),v.defaultInstallmentCount(),v.installmentIntervalDays(),v.minimumInstallmentAmount(),v.paymentTermDays(),v.reminderEnabled(),v.reminderDaysAfterDue(),v.dunning1Enabled(),v.dunning1DaysAfterReminder(),v.dunning1Fee(),v.dunning2Enabled(),v.dunning2DaysAfterDunning1(),v.dunning2Fee(),v.dunning3Enabled(),v.dunning3DaysAfterDunning2(),v.dunning3Fee(),v.collectionEnabled(),v.collectionDaysAfterDunning3(),v.annualInterestPercent(),v.automaticDocumentCreation(),v.manualApprovalRequired(),v.publishToPortal(),v.portalReadAloudEnabled(),v.automaticEmailDispatch()};for(int j=0;j<k.length;j++)put(k[j],x[j],u);return load();}
 private void putMissing(String k,Object v){jdbc.update("INSERT IGNORE INTO gam_settings(setting_key,setting_value,updated_by) VALUES(?,?,'system')",k,String.valueOf(v));} private void put(String k,Object v,String u){jdbc.update("INSERT INTO gam_settings(setting_key,setting_value,updated_by) VALUES(?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by),updated_at=CURRENT_TIMESTAMP",k,String.valueOf(v),u);} private String s(String k,String f){var a=jdbc.query("SELECT setting_value FROM gam_settings WHERE setting_key=?",(ResultSet r,int z)->r.getString(1),k);return a.isEmpty()?f:a.get(0);} private boolean b(String k,boolean f){return Boolean.parseBoolean(s(k,String.valueOf(f)));}private int i(String k,int f){try{return Integer.parseInt(s(k,String.valueOf(f)));}catch(Exception e){return f;}}private BigDecimal n(String k,BigDecimal f){try{return new BigDecimal(s(k,f.toPlainString()));}catch(Exception e){return f;}}
}
