package de.kopfzentrum.gam.communication;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import java.time.LocalDate;import java.util.List;
@Repository
public class CommunicationWorkflowRepository{
 private final JdbcTemplate jdbc;private final CommunicationWorkflowSettingsRepository settings;
 public CommunicationWorkflowRepository(JdbcTemplate jdbc,CommunicationWorkflowSettingsRepository settings){this.jdbc=jdbc;this.settings=settings;jdbc.execute("""
 CREATE TABLE IF NOT EXISTS communication_workflow_item(
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,channel VARCHAR(30) NOT NULL DEFAULT 'E-Mail',direction VARCHAR(20) NOT NULL DEFAULT 'EINGANG',sender VARCHAR(255) NULL,recipient VARCHAR(255) NULL,subject VARCHAR(500) NOT NULL,message TEXT NULL,responsible VARCHAR(120) NULL,priority VARCHAR(20) NOT NULL DEFAULT 'mittel',status VARCHAR(30) NOT NULL DEFAULT 'NEU',due_date DATE NULL,result_note TEXT NULL,created_by VARCHAR(100) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_by VARCHAR(100) NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_comm_status(status),INDEX idx_comm_due(due_date),INDEX idx_comm_responsible(responsible))
 """);}
 public List<CommunicationWorkflowItem> list(String q,String status,String responsible){StringBuilder sql=new StringBuilder("SELECT * FROM communication_workflow_item WHERE 1=1");java.util.ArrayList<Object> p=new java.util.ArrayList<>();if(q!=null&&!q.isBlank()){sql.append(" AND (subject LIKE ? OR message LIKE ? OR sender LIKE ? OR recipient LIKE ?)");String x="%"+q.trim()+"%";p.add(x);p.add(x);p.add(x);p.add(x);}if(status!=null&&!status.isBlank()&&!"all".equalsIgnoreCase(status)){sql.append(" AND status=?");p.add(status);}if(responsible!=null&&!responsible.isBlank()){sql.append(" AND responsible LIKE ?");p.add("%"+responsible.trim()+"%");}sql.append(" ORDER BY CASE status WHEN 'NEU' THEN 0 WHEN 'IN_BEARBEITUNG' THEN 1 WHEN 'WARTET_AUF_ANTWORT' THEN 2 WHEN 'ERLEDIGT' THEN 3 ELSE 4 END, COALESCE(due_date,'9999-12-31'), updated_at DESC LIMIT 500");return jdbc.query(sql.toString(),this::map,p.toArray());}
 public CommunicationWorkflowItem get(long id){return jdbc.queryForObject("SELECT * FROM communication_workflow_item WHERE id=?",this::map,id);}
 public CommunicationWorkflowItem create(CommunicationWorkflowRequest r,String user){var s=settings.load();if(!s.enabled())throw new IllegalStateException("Kommunikationsworkflow ist deaktiviert.");String subject=clean(r.subject());if(subject.isBlank())throw new IllegalArgumentException("Betreff fehlt.");String responsible=clean(r.responsible());if(s.requireResponsiblePerson()&&responsible.isBlank())throw new IllegalArgumentException("Verantwortlicher fehlt.");LocalDate due=parse(r.dueDate());if(due==null&&s.requireDueDate())throw new IllegalArgumentException("Fälligkeitsdatum fehlt.");if(due==null&&s.defaultDueDays()>0)due=LocalDate.now().plusDays(s.defaultDueDays());jdbc.update("INSERT INTO communication_workflow_item(channel,direction,sender,recipient,subject,message,responsible,priority,status,due_date,result_note,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",value(r.channel(),"E-Mail"),value(r.direction(),"EINGANG"),clean(r.sender()),clean(r.recipient()),subject,clean(r.message()),responsible,value(r.priority(),"mittel"),normalizeStatus(r.status()),due,clean(r.resultNote()),user,user);Long id=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);return get(id);}
 public CommunicationWorkflowItem update(long id,CommunicationWorkflowRequest r,String user){var s=settings.load();String responsible=clean(r.responsible());if(s.requireResponsiblePerson()&&responsible.isBlank())throw new IllegalArgumentException("Verantwortlicher fehlt.");LocalDate due=parse(r.dueDate());if(s.requireDueDate()&&due==null)throw new IllegalArgumentException("Fälligkeitsdatum fehlt.");String status=normalizeStatus(r.status());if("ERLEDIGT".equals(status)&&clean(r.resultNote()).isBlank())throw new IllegalArgumentException("Zum Abschluss ist eine Ergebnisnotiz erforderlich.");jdbc.update("UPDATE communication_workflow_item SET channel=?,direction=?,sender=?,recipient=?,subject=?,message=?,responsible=?,priority=?,status=?,due_date=?,result_note=?,updated_by=? WHERE id=?",value(r.channel(),"E-Mail"),value(r.direction(),"EINGANG"),clean(r.sender()),clean(r.recipient()),clean(r.subject()),clean(r.message()),responsible,value(r.priority(),"mittel"),status,due,clean(r.resultNote()),user,id);return get(id);}
 public void delete(long id){jdbc.update("DELETE FROM communication_workflow_item WHERE id=?",id);}
 private CommunicationWorkflowItem map(java.sql.ResultSet rs,int n)throws java.sql.SQLException{return new CommunicationWorkflowItem(rs.getLong("id"),rs.getString("channel"),rs.getString("direction"),rs.getString("sender"),rs.getString("recipient"),rs.getString("subject"),rs.getString("message"),rs.getString("responsible"),rs.getString("priority"),rs.getString("status"),rs.getObject("due_date",LocalDate.class),rs.getString("result_note"),rs.getString("created_by"),rs.getTimestamp("created_at").toLocalDateTime(),rs.getString("updated_by"),rs.getTimestamp("updated_at").toLocalDateTime());}
 private static String clean(String v){return v==null?"":v.trim();}private static String value(String v,String d){return clean(v).isBlank()?d:clean(v);}private static LocalDate parse(String v){try{return clean(v).isBlank()?null:LocalDate.parse(v);}catch(Exception e){throw new IllegalArgumentException("Ungültiges Fälligkeitsdatum.");}}private static String normalizeStatus(String s){String v=value(s,"NEU").toUpperCase().replace(' ','_');return switch(v){case "NEU","IN_BEARBEITUNG","WARTET_AUF_ANTWORT","ERLEDIGT","ARCHIVIERT"->v;default->throw new IllegalArgumentException("Unbekannter Kommunikationsstatus: "+s);};}
}
